title: 主張書面と認否、山田悠一郎裁判官判決文、坂巻陽士裁判官判決文
description: ＥＮＥＯＳ（エネオス）の内部通報制度とコンプライアンス対応をめぐる訴訟について、山田悠一郎裁判官・坂巻陽士裁判官の判決文を通じて、日本の通報窓口における調査の透明性、心理的安全性との関係を検証しています。
logo: logo.png
exclude_patterns: [_build, _00hikae, README.md, memo.txt]

html:
  announcement: <a class="reference external" href="https://minnanosaiban.github.io/hotline/judgment2025.html">東京地裁判決</a>と<a class="reference external" href="https://minnanosaiban.github.io/hotline/_static/eneos-kouso1.pdf">控訴理由書</a>を掲載しました。
  favicon: "_static/favicon.png" 
  baseurl: https://minnanosaiban.github.io/hotline/
  use_multitoc_numbering: true
  home_page_in_navbar: true
  use_edit_page_button: false
  use_repository_button: true
  use_issues_button: false
  show_navbar_previous: false
  show_navbar_next: false

parse:
  myst_enable_extensions: 
    - amsmath
    - attrs_inline
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist

repository:
  url: https://github.com/minnanosaiban/hotline
  branch: main